// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart'
    show Firebase, FirebaseApp, FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static Future<void> loadEnv() async {
    if (!dotenv.isInitialized) {
      await dotenv.load(fileName: '.env');
    }
  }

  /// On Android/iOS uses [google-services.json] / GoogleService-Info.plist so
  /// FCM auth stays aligned with native config (not a separate .env API key).
  static Future<FirebaseApp> initialize() async {
    if (kIsWeb) {
      await loadEnv();
      return Firebase.initializeApp(options: currentPlatform);
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
      case TargetPlatform.iOS:
        return Firebase.initializeApp();
      default:
        await loadEnv();
        return Firebase.initializeApp(options: currentPlatform);
    }
  }

  static String _requiredEnv(String key) {
    final value = dotenv.env[key]?.trim() ?? '';
    if (value.isEmpty) {
      throw StateError(
        'Missing $key. Copy .env.example to .env and fill in the Firebase keys.',
      );
    }
    return value;
  }

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get android => FirebaseOptions(
    apiKey: _requiredEnv('FIREBASE_ANDROID_API_KEY'),
    appId: '1:910989560751:android:f6cd4862807114ac4c3d5a',
    messagingSenderId: '910989560751',
    projectId: 'data-portal-2c403',
    storageBucket: 'data-portal-2c403.firebasestorage.app',
  );

  static FirebaseOptions get ios => FirebaseOptions(
    apiKey: _requiredEnv('FIREBASE_IOS_API_KEY'),
    appId: '1:910989560751:ios:091e260ebfa4f1c24c3d5a',
    messagingSenderId: '910989560751',
    projectId: 'data-portal-2c403',
    storageBucket: 'data-portal-2c403.firebasestorage.app',
    iosBundleId: 'com.infocare.dataportalsurvey',
  );
}
